name: Continued Integration

on:
  push:
    branches: [ dev ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Compile Angular App
        working-directory: ./frontend
        run: |
          npm install
          npm run build
          cd dist
          dir
          rm 3rdpartylicenses.txt
          mkdir ../../app/static
          mv -v ./* ../../app/static/
